//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string StreetName { get; set; }
        public string CityName { get; set; }
        public int PostalCode { get; set; }
        public string ContactNo { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
