//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public Prescription()
        {
            this.PrescriptionItems = new HashSet<PrescriptionItem>();
        }
    
        public int PrescriptionId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime Date { get; set; }
        public string Reference { get; set; }
        public int UserId { get; set; }
        public decimal Total { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<PrescriptionItem> PrescriptionItems { get; set; }
    }
}
