//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.PurchaseItems = new HashSet<PurchaseItem>();
        }
    
        public int PurchaseId { get; set; }
        public int SupplierId { get; set; }
        public System.DateTime Date { get; set; }
        public string ReferenceNo { get; set; }
        public int UserId { get; set; }
        public decimal Total { get; set; }
    
        public virtual Supllier Supllier { get; set; }
        public virtual ICollection<PurchaseItem> PurchaseItems { get; set; }
    }
}
